# Generated by Django 5.1.1 on 2025-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0006_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="bdxx7wpf7R29W4wOYbgszEuXQj99HmQO",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
